name: pr-checks

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  checks:
    name: Basic stuff
    runs-on: ubuntu-latest
    outputs:
      things: ${{ steps.changed_files.outputs.added_modified }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: collect list of added/modified monitors
        uses: Ana06/get-changed-files@v2.1.0
        id: changed_files
        with:
          format: 'json'
          filter: |
            stuff/*.txt
      - name: get things out of stuff
        uses: actions/github-script@v6
        env:
          STUFF: ${{ steps.changed_files.outputs.added_modified }}
          STUFF_TOJSON: ${{ toJSON(steps.changed_files.outputs.added_modified) }}
        with:
          script: |
            console.log(process.env.STUFF)
            console.log(process.env.STUFF_TOJSON)
      # - name: debug
      #   run: echo "${{ steps.changed_files.outputs.added_modified }}"
      # - name: debug again to JSON
      #   run: echo "${{ toJSON(steps.changed_files.outputs.added_modified) }}"
      # - name: debug again from JSON
      #   run: echo "${{ fromJSON(steps.changed_files.outputs.added_modified) }}"

  tests:
    name: Specific stuff on only added and modified files
    runs-on: ubuntu-latest
    needs:
      - checks
    strategy:
      matrix:
        thing: ${{ fromJSON(needs.checks.outputs.things) }}
    steps:
      - name: do some specific stuff for this thing
        run: echo "${{ matrix.thing }}"
