name: pr-checks

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  checks:
    name: Basic stuff
    runs-on: ubuntu-latest
    outputs:
      things: ${{ steps.script.outputs.result }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: collect list of added/modified monitors
        uses: Ana06/get-changed-files@v2.1.0
        id: changed_files
        with:
          format: 'json'
          filter: |
            xxx/*.txt
      - name: get things out of stuff
        uses: actions/github-script@v6
        id: script
        env:
          STUFF: ${{ steps.changed_files.outputs.added_modified }}
          STUFF_TOJSON: ${{ toJSON(steps.changed_files.outputs.added_modified) }}
        with:
          script: |
            const stuff = JSON.parse(process.env.STUFF)
            const things = stuff.map(s => {
              return s.replace('xxx/', '').replace('.txt', '')
            })
            return things

  tests:
    name: Specific stuff on only added and modified files
    runs-on: ubuntu-latest
    needs:
      - checks
    if: ${{ needs.checks.outputs.things != '[]' && needs.checks.outputs.things != '' }}
    strategy:
      matrix:
        thing: ${{ fromJSON(needs.checks.outputs.things) }}
    steps:
      - name: do some specific stuff for this thing
        run: echo "${{ matrix.thing }}"
