name: pr-checks

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  checks:
    name: Basic stuff
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: collect list of added/modified monitors
        uses: Ana06/get-changed-files@v2.1.0
        id: changed_files
        with:
          format: 'json'
          filter: |
            stuff/*.txt
      - name: save stuff in readable format
        uses: actions/github-script@v6
        env:
          STUFF: ${{ steps.changed_files.outputs.added_modified }}
        with:
          script: |
            console.log(`${process.env.STUFF}`)

  tests:
    name: Specific stuff on only added and modified files
    runs-on: ubuntu-latest
    needs:
      - checks
    strategy:
      matrix:
        product: ${{ fromJSON(needs.checks.changed_files.outputs.added_modified) }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: do some specific stuff
        run: echo "${{ matrix.product }}"
